// Copyright © 2025 blackshirt.
// Use of this source code is governed by an MIT license
// that can be found in the LICENSE file.
//
// This file contains low-level primitive in the mean of Galois-Field
// element over 448-bits for curve448 operations.
module curve448

import math.bits
import math.unsigned

// Field is an an opaque represents the field of 448-bits integer of GF modulo p = 2⁴⁴⁸ - 2²²⁴ - 1.
// Its represented as unsaturated (redundant) limb in the form of 8 of 56-bits limbs, ie:
//     t.e0*2⁰ + t.e1*2⁵⁶ + t.e2*2¹¹² + t.e3*2¹⁶⁸ + t.e4*2²²⁴ + t.e5*2²⁸⁰ + t.e6*2³³⁶ + t.e7*2³⁹²
//
@[noinit]
struct Field {
mut:
	// Between operations, all limbs are expected to be lower than 2⁵⁷ (ie, fits in 56-bits)
	el [8]u64
}

// new_field creates an empty field
@[inline]
fn new_field() Field {
	return fe_zero
}

// The size of field limb, in bits
const fe_limb_size = 56
// Masking value for field's limb value, ie, 0x00ff_ffff_ffff_ffff
const fe_masklow_56bits = u64(0x00ff_ffff_ffff_ffff)

// zero field element
const fe_zero = Field{
	el: [u64(0), 0, 0, 0, 0, 0, 0, 0]!
}

// one field element
const fe_one = Field{
	el: [u64(1), 0, 0, 0, 0, 0, 0, 0]!
}

// fe_p is a prime modulus of the field, ie, p = 2⁴⁴⁸ - 2²²⁴ - 1
const fe_p = Field{
	el: [u64(0x00FF_FFFF_FFFF_FFFF), u64(0x00FF_FFFF_FFFF_FFFF), u64(0x00FF_FFFF_FFFF_FFFF),
		u64(0x00FF_FFFF_FFFF_FFFF), u64(0x00FF_FFFF_FFFF_FFFE), u64(0x00FF_FFFF_FFFF_FFFF),
		u64(0x00FF_FFFF_FFFF_FFFF), u64(0x00FF_FFFF_FFFF_FFFF)]!
}

// fe_clear overwrites a field element in-place. It is intended for best-effort
// source-level wiping of temporary values that may contain secret-dependent data
// after use. Strict secure-zeroization guarantees require auditing generated
// C/assembly or replacing this with a compiler-resistant wipe primitive.
@[direct_array_access; inline]
fn fe_clear(mut z Field) {
	for i := 0; i < 8; i++ {
		z.el[i] = 0
	}
}

// fe_add performs modular field addition: z = a + b (mod p).
// It adds the elements limb-by-limb, extracts the carries, and performs a single
// reduction step using the Solinas prime identity: 2^448 = 2^224 + 1 (mod p).
@[direct_array_access; inline]
fn fe_add(mut z Field, a Field, b Field) {
	// c holds the carry bits extracted from each 56-bit limb addition.
	// Since we are adding two 56-bit (or slightly larger) limbs, the sum can exceed
	// 56 bits. The carry bit c[i] will be either 0 or 1.
	mut c := [8]u64{}
	// Operations like fe_add(mut a, a, b) corrupt outputs because z.el[i] overwrites
	// input limbs during early loop iterations.Write to an isolated local
	// struct res before copying to destination z
	mut res := Field{}

	// Step 1: Add limbs individually.
	// We iterate through all 8 limbs. For each limb, we compute the sum of the
	// limbs of a and b, extract the carry (bits above the 56-bit boundary),
	// and mask the limb to retain only the lower 56 bits.
	for i := 0; i < 8; i++ {
		res.el[i] = a.el[i] + b.el[i]
		c[i] = res.el[i] >> fe_limb_size
		res.el[i] = (res.el[i] & fe_masklow_56bits)
	}

	// Step 2: Apply modular reduction for Curve448.
	// The Curve448 modulus is p = 2^448 - 2^224 - 1, which implies the identity:
	//     2^448 = 2^224 + 1 (mod p)
	// Any overflow carry from the highest limb (limb 7, representing 2^392)
	// corresponds to a carry of 2^448. By the identity, this carry is reduced to:
	//     c[7] * 2^224 + c[7] * 1
	// Therefore, we add c[7] to the 0-th limb (representing 2^0) and the 4th limb
	// (representing 2^224).
	res.el[0] += c[7]
	res.el[4] += c[7]

	// Step 3: Propagate the remaining carries to the next higher limbs.
	// For each limb from 1 to 7, we add the carry bit generated by the addition
	// of the immediately preceding limb (c[i-1]).
	for i := 1; i < 8; i++ {
		res.el[i] += c[i - 1]
	}
	fe_carry_propagates(mut res)
	fe_clone(mut z, res)
}

// fe_sub performs modular field subtraction: z = a - b (mod p).
// To prevent underflow, it first adds 2 * p (a multiple of the modulus) to a,
// subtracts b, extracts the carries, and applies a reduction step.
@[direct_array_access; inline]
fn fe_sub(mut z Field, a Field, b Field) {
	// c holds the carry/borrow bits extracted from each limb subtraction.
	mut c := [8]u64{}

	// Step 1: Perform subtraction with biased limbs.
	// Since a.el[i] could be smaller than b.el[i], a direct subtraction could underflow
	// and wrap around. To guarantee that the result remains positive and fits in u64,
	// we add 2 * p.el[i] (which is at least 2^57 - 4) to a.el[i] before subtracting b.el[i].
	// We then extract the carry (which acts as a borrow flag) and mask the limb.
	for i := 0; i < 8; i++ {
		// add by 2 * p.el[i]
		z.el[i] = (a.el[i] + (fe_p.el[i] << 1)) - b.el[i]
		c[i] = z.el[i] >> fe_limb_size
		z.el[i] = z.el[i] & fe_masklow_56bits
	}

	// Step 2: Apply the modular reduction.
	// Just like in addition, any carry from the highest limb (c[7]) represents
	// 2^448. We reduce it by adding c[7] to limb 0 (representing 2^0) and limb 4
	// (representing 2^224).
	z.el[0] += c[7]
	z.el[4] += c[7]

	// Step 3: Propagate the carries.
	// Add the carry bit from the previous limb to the current limb.
	for i := 1; i < 8; i++ {
		z.el[i] += c[i - 1]
	}

	fe_carry_propagates(mut z)
}

// fe_negate negates a field element: z = -a (mod p).
// It subtracts each limb of a from the corresponding limb of 2 * p,
// propagates the carries, and applies modular reduction.
@[direct_array_access; inline]
fn fe_negate(mut z Field, a Field) {
	// Step 1: Subtract each limb of a from 2 * p.
	// The limbs of 2 * p are:
	//     2 * p.el[i] = 2^57 - 2 = 0x01fffffffffffffe  (for i != 4)
	//     2 * p.el[4] = 2^57 - 4 = 0x01fffffffffffffc  (for i == 4)
	// This subtraction is guaranteed not to underflow because a.el[i] < 2^57.
	z.el[0] = u64(0x01fffffffffffffe) - a.el[0]
	z.el[1] = u64(0x01fffffffffffffe) - a.el[1]
	z.el[2] = u64(0x01fffffffffffffe) - a.el[2]
	z.el[3] = u64(0x01fffffffffffffe) - a.el[3]
	z.el[4] = u64(0x01fffffffffffffc) - a.el[4]
	z.el[5] = u64(0x01fffffffffffffe) - a.el[5]
	z.el[6] = u64(0x01fffffffffffffe) - a.el[6]
	z.el[7] = u64(0x01fffffffffffffe) - a.el[7]

	// Step 2: Extract and propagate the carries.
	mut c := [8]u64{}
	for i := 0; i < 8; i++ {
		c[i] = z.el[i] >> fe_limb_size
		z.el[i] = (z.el[i] & fe_masklow_56bits)
	}

	// Step 3: Apply modular reduction using the Solinas prime identity:
	//     2^448 = 2^224 + 1 (mod p)
	z.el[0] += c[7]
	z.el[4] += c[7]

	// Step 4: Propagate the carries to higher limbs.
	for i := 1; i < 8; i++ {
		z.el[i] += c[i - 1]
	}

	// final carry
	fe_carry_propagates(mut z)
}

// fe_clone clones x into z
@[direct_array_access; inline]
fn fe_clone(mut z Field, x Field) {
	for i := 0; i < 8; i++ {
		z.el[i] = x.el[i]
	}
}

// fe_mult multiplies a with b and stores into z, ie, z = a * b (mod p)
//
// This is the most intensive routines.
// TODO: optimize it with some well-known algorithm
@[direct_array_access]
fn fe_mult(mut z Field, x Field, y Field) {
	// fe_mult_generic(mut z, x, y)
	fe_mult_karatsuba(mut z, x, y)
}

// fe_mult_karatsuba multiplies two field elements using a two-way Karatsuba split.
//
// The input is split into low and high 224-bit halves, each containing four
// 56-bit limbs:
//
//     x = x0 + x1*B⁴,  y = y0 + y1*B⁴,  B = 2⁵⁶
//
// Karatsuba computes the unreduced product with three 4-limb products instead
// of four:
//
//     z0 = x0*y0
//     z2 = x1*y1
//     z1 = (x0+x1)*(y0+y1) - z0 - z2
//     x*y = z0 + z1*B⁴ + z2*B⁸
//
// The resulting 15 polynomial limbs are then folded modulo
// p = 2⁴⁴⁸ - 2²²⁴ - 1 by B⁸ = B⁴ + 1. Terms at B⁸..B¹⁴ are first folded to
// positions i-8 and i-4; terms that land at B⁸..B¹⁰ from the first fold are
// folded once more. All arithmetic stays below 128 bits: the largest product
// term is a sum of a handful of 57-bit-by-57-bit products.
@[direct_array_access; inline]
fn fe_mult_karatsuba(mut z Field, x Field, y Field) {
	mut z0 := [7]unsigned.Uint128{}
	mut z1 := [7]unsigned.Uint128{}
	mut z2 := [7]unsigned.Uint128{}

	mul_4limb_schoolbook(mut z0, x.el[0], x.el[1], x.el[2], x.el[3], y.el[0], y.el[1], y.el[2],
		y.el[3])
	mul_4limb_schoolbook(mut z2, x.el[4], x.el[5], x.el[6], x.el[7], y.el[4], y.el[5], y.el[6],
		y.el[7])

	x01_0 := x.el[0] + x.el[4]
	x01_1 := x.el[1] + x.el[5]
	x01_2 := x.el[2] + x.el[6]
	x01_3 := x.el[3] + x.el[7]
	y01_0 := y.el[0] + y.el[4]
	y01_1 := y.el[1] + y.el[5]
	y01_2 := y.el[2] + y.el[6]
	y01_3 := y.el[3] + y.el[7]
	mul_4limb_schoolbook(mut z1, x01_0, x01_1, x01_2, x01_3, y01_0, y01_1, y01_2, y01_3)

	// apply reduction
	for i := 0; i < 7; i++ {
		z1[i] = sub_128(sub_128(z1[i], z0[i]), z2[i])
	}

	mut r := [15]unsigned.Uint128{}
	for i := 0; i < 7; i++ {
		r[i] = add_128(r[i], z0[i])
		r[i + 4] = add_128(r[i + 4], z1[i])
		r[i + 8] = add_128(r[i + 8], z2[i])
	}

	// Fold high polynomial limbs with B⁸ = B⁴ + 1.
	// Correct Solinas reduction mod p = 2^448 - 2^224 - 1
	// Max product limb index is r[14] (0 to 14 = 15 total limbs)

	mut t0 := add_128(r[0], add_128(r[8], r[12]))
	mut t1 := add_128(r[1], add_128(r[9], r[13]))
	mut t2 := add_128(r[2], add_128(r[10], r[14]))
	mut t3 := add_128(r[3], r[11]) // Note: r[15] is 0, so omitted

	// High limbs fold with (r[i+4] + r[i+8] + 2*r[i+12])
	mut r12_x2 := lsh_128(r[12])
	mut r13_x2 := lsh_128(r[13])
	mut r14_x2 := lsh_128(r[14])

	mut t4 := add_128(r[4], add_128(r[8], r12_x2))
	mut t5 := add_128(r[5], add_128(r[9], r13_x2))
	mut t6 := add_128(r[6], add_128(r[10], r14_x2))
	mut t7 := add_128(r[7], r[11]) // Note: r[15] is 0, so omitted

	reduce_8limb_product(mut z, mut t0, mut t1, mut t2, mut t3, mut t4, mut t5, mut t6, mut t7)

	/*
	mut t0 := add_128(r[0], r[8])
	t0 = add_128(t0, r[12])
	mut t1 := add_128(r[1], r[9])
	t1 = add_128(t1, r[13])
	mut t2 := add_128(r[2], r[10])
	t2 = add_128(t2, r[14])
	mut t3 := add_128(r[3], r[11])
	mut t4 := add_128(r[4], r[8])
	t4 = add_128(t4, lsh_128(r[12]))
	mut t5 := add_128(r[5], r[9])
	t5 = add_128(t5, lsh_128(r[13]))
	mut t6 := add_128(r[6], r[10])
	t6 = add_128(t6, lsh_128(r[14]))
	mut t7 := add_128(r[7], r[11])
	*/
	// reduce_8limb_product(mut z, mut t0, mut t1, mut t2, mut t3, mut t4, mut t5, mut t6, mut t7)

	// Best-effort source-level clearing of reusable stack slots. For strict
	// zeroization guarantees, verify the generated C/assembly does not elide it.
	clear_uint128x7(mut z0)
	clear_uint128x7(mut z1)
	clear_uint128x7(mut z2)
	clear_uint128x15(mut r)
}

// square squares a field, ie, z = a*a (mod p)
@[direct_array_access; inline]
fn fe_sqr(mut z Field, a Field) {
	fe_mult_karatsuba(mut z, a, a)
}

// fe_mult_32 multiplies x with u32 (mod p)
@[direct_array_access; inline]
fn fe_mult_32(mut z Field, x Field, y u32) {
	// 56-bits multiplication, returns u64 (lo, hi) pair
	x0lo, x0hi := mult_56(x.el[0], y)
	x1lo, x1hi := mult_56(x.el[1], y)
	x2lo, x2hi := mult_56(x.el[2], y)
	x3lo, x3hi := mult_56(x.el[3], y)
	x4lo, x4hi := mult_56(x.el[4], y)
	x5lo, x5hi := mult_56(x.el[5], y)
	x6lo, x6hi := mult_56(x.el[6], y)
	x7lo, x7hi := mult_56(x.el[7], y)

	// reduction
	z.el[0] = x0lo + x7hi
	z.el[1] = x1lo + x0hi
	z.el[2] = x2lo + x1hi
	z.el[3] = x3lo + x2hi
	z.el[4] = x4lo + x3hi + x7hi
	z.el[5] = x5lo + x4hi
	z.el[6] = x6lo + x5hi
	z.el[7] = x7lo + x6hi

	fe_carry_propagates(mut z)
}

// set_bytes sets the field values from bytes array
@[direct_array_access; inline]
fn (mut z Field) set_bytes(b []u8) ! {
	if b.len != 56 {
		return error('bad set_bytes input')
	}

	// Parse little-endian limbs
	for i := 0; i < 8; i++ {
		mut limb := u64(0)
		for j := 0; j < 7; j++ {
			limb |= u64(b[i * 7 + j]) << (j * 8)
		}
		z.el[i] = limb
	}
	// Verify canonicality: x must be strictly less than p
	if !z.is_canonical() {
		return error('non-canonical field element (x >= p)')
	}
}

// Check if field element is in canonical form [0, p-1]
fn (x Field) is_canonical() bool {
	// We directly checks individual limbs with z.el[i] > fe_masklow_56bits.
	// However, if a field element has unpropagated carries (e.g., el[0] = 2^56
	// while the total value is still modulo $< p$),
	// it will incorrectly return false, so we reduce it firts
	mut z := x
	fe_reduce(mut z)
	// Return false if any limb exceeds 56 bits
	for i := 0; i < 8; i++ {
		if z.el[i] > fe_masklow_56bits { return false }
	}

	// Test if z >= p by computing carry of z + (2^224 + 1)
	mut c := u64(1) // +1 bit 0
	for i := 0; i < 8; i++ {
		add := if i == 4 { u64(1) } else { u64(0) } // +1 bit 224
		sum := z.el[i] + add + c
		c = sum >> 56
	}
	// If c == 1, then z + 2^224 + 1 >= 2^448 => z >= p
	return c == 0
}

// bytes serializes reduced x field into bytes
@[direct_array_access; inline]
fn (mut x Field) bytes() []u8 {
	mut dst := []u8{len: 56}
	x.to_bytes(mut dst) or { panic('error on bytes call') }
	return dst
}

// to_bytes serializes reduced x Field into bytes in little-endian form.
@[direct_array_access; inline]
fn (mut x Field) to_bytes(mut dst []u8) ! {
	if dst.len != 56 {
		return error('bad destination size')
	}
	// reduces the field first
	fe_reduce(mut x)

	// serialized x field in little-endian form
	for i := 0; i < 7; i++ {
		dst[i + 0] = u8(x.el[0] >> u64(i * 8))
		dst[i + 7] = u8(x.el[1] >> u64(i * 8))
		dst[i + 14] = u8(x.el[2] >> u64(i * 8))
		dst[i + 21] = u8(x.el[3] >> u64(i * 8))
		dst[i + 28] = u8(x.el[4] >> u64(i * 8))
		dst[i + 35] = u8(x.el[5] >> u64(i * 8))
		dst[i + 42] = u8(x.el[6] >> u64(i * 8))
		dst[i + 49] = u8(x.el[7] >> u64(i * 8))
	}
}

// fe_reduce reduces x field (mod p)
@[direct_array_access; inline]
fn fe_reduce(mut x Field) {
	// by the light reduction, we have a field element representation
	// x < 2⁴⁴⁸ + 2²³² + 2⁸, but we need x < 2⁴⁴⁸ - 2²²⁴ - 1 (p).

	fe_carry_propagates(mut x)

	// Test if x + 2^224 + 1 >= 2^448 (equivalent to x >= p)
	mut c := u64(1)
	for i := 0; i < 8; i++ {
		// Branchless offset addition: adds 1 at limb 4 without ternary operators
		add := u64(i == 4)
		s := x.el[i] + add + c
		c = s >> fe_limb_size
	}

	// Reduce by adding c*(2^224 + 1)
	x.el[0] += c
	x.el[4] += c

	c = 0
	for i := 0; i < 8; i++ {
		s := x.el[i] + c
		x.el[i] = s & fe_masklow_56bits
		c = s >> fe_limb_size
	}
	// Ensure any remaining carry is folded (guarantee fully reduced result)
	fe_carry_propagates(mut x)
}

// fe_carry_propagates performs a single pass of carry propagation across the field.
// It extracts the carry from each limb and adds it to the next higher limb,
// while applying the Solinas prime reduction on the overflow carry from limb 7.
@[direct_array_access; inline]
fn fe_carry_propagates(mut x Field) {
	// In rare edge cases where upper limbs are near their maximum value
	// (e.g., right after c[7] reduction addition to el[0] and el[4]),
	// two carry passes might still leave a single bit overflow in el[0] or el[4].
	// Exactly 2 passes are mathematically proven to absorb all Solinas carries (2^448 = 2^224 + 1)
	mut c := u64(0)
	for _ in 0 .. 2 {
		for i := 0; i < 8; i++ {
			s := x.el[i] + c
			x.el[i] = s & fe_masklow_56bits
			c = s >> fe_limb_size
		}
		// Fold carry modulo p = 2^448 - 2^224 - 1
		x.el[0] += c
		x.el[4] += c
		c = 0
	}
}

// fe_equal checks whether a == b, return 1 if it true, 0 otherwise
@[direct_array_access; inline]
fn fe_equal(a Field, b Field) bool {
	return fe_cmp(a, b) == 1
}

// fe_cmp compares the fields between a and b modulo p (fully reduces both first).
// Returns 1 if a == b (mod p), and 0 otherwise.
// This function is implemented to run in constant-time.
@[direct_array_access; inline]
fn fe_cmp(a Field, b Field) int {
	// First, reduce both elements to their canonical representation.
	mut x := a
	mut y := b
	fe_reduce(mut x)
	fe_reduce(mut y)

	// Compare the limbs in constant-time.
	// Any difference in any limb will set the bits in `c`.
	mut c := u64(0)
	// Compare x and y
	for i := 0; i < 8; i++ {
		// Constant time implementation
		c |= x.el[i] ^ y.el[i]
	}

	// Return 1 if equal (diff == 0), else 0 in constant-time
	return int(1 - ((c | (0 - c)) >> 63))
}

// fe_cselect set z to a if c == 1, and to b if c == 0
@[direct_array_access; inline]
fn fe_cselect(mut z Field, a Field, b Field, c int) {
	m := mask_64bits(c)
	// Select between a and b
	for i := 0; i < 8; i++ {
		// Constant time implementation
		z.el[i] = (a.el[i] & m) | (b.el[i] & ~m)
	}
}

// fe_cswap perform constant-time conditional swap, ie, swaps a and b if c == 1 or leaves them unchanged if c == 0.
@[direct_array_access; inline]
fn fe_cswap(mut a Field, mut b Field, c int) {
	// The mask is the all-1 or all-0 word
	m := mask_64bits(c)
	mut dummy := u64(0)

	// Conditional swap with constant time implementation
	for i := 0; i < 8; i++ {
		dummy = m & (a.el[i] ^ b.el[i])
		a.el[i] ^= dummy
		b.el[i] ^= dummy
	}
}

// fe_inverse performs modular multiplicative inverse, ie, z = 1/x
@[direct_array_access; inline]
fn fe_inverse(mut z Field, x Field) {
	mut t := Field{}
	fe_power446(mut t, x)
	fe_sqr(mut t, t)
	fe_sqr(mut t, t) // 2^448 - 2^224 - 4

	fe_mult(mut z, t, x) // 2^448 - 2^224 - 3
}

// fe_power446 sets v = v ⁽ᵖ⁻³⁾/⁴ (mod p), and returns v.
// where (p-3)/4 is 2⁴⁴⁶ - 2²²² - 1.
@[direct_array_access; inline]
fn fe_power446(mut v Field, z Field) {
	mut t1 := Field{}
	mut t2 := Field{}
	mut t3 := Field{}

	fe_sqr(mut t1, z) // 2^1
	fe_sqr(mut t2, t1) // 2^2
	fe_mult(mut t3, z, t1) //
	fe_mult(mut t3, t3, t2) // 2^3 - 1

	mut t6 := Field{} //
	fe_sqr(mut t6, t3)
	fe_sqr(mut t6, t6)
	fe_sqr(mut t6, t6)
	fe_mult(mut t6, t6, t3) // 2^6 - 1

	mut t9 := Field{}
	fe_sqr(mut t9, t6)
	fe_sqr(mut t9, t9)
	fe_sqr(mut t9, t9)
	fe_mult(mut t9, t9, t3) // 2^9 - 1

	mut t18 := Field{}
	fe_sqr(mut t18, t9)
	for i := 1; i < 9; i++ {
		fe_sqr(mut t18, t18)
	}
	fe_mult(mut t18, t18, t9) // 2^18 - 1

	mut t37 := Field{}
	fe_sqr(mut t37, t18)
	for i := 1; i < 18; i++ {
		fe_sqr(mut t37, t37)
	}
	fe_mult(mut t37, t37, t18)
	fe_sqr(mut t37, t37)
	fe_mult(mut t37, t37, z) // 2^37 - 1

	mut t111 := Field{}
	fe_sqr(mut t111, t37)
	for i := 1; i < 37; i++ {
		fe_sqr(mut t111, t111)
	}
	fe_mult(mut t111, t111, t37)
	for i := 0; i < 37; i++ {
		fe_sqr(mut t111, t111)
	}
	fe_mult(mut t111, t111, t37) // 2^111 - 1

	mut t222 := Field{}
	fe_sqr(mut t222, t111)
	for i := 1; i < 111; i++ {
		fe_sqr(mut t222, t222)
	}
	fe_mult(mut t222, t222, t111) // 2^222 - 1

	mut t223 := Field{}
	fe_sqr(mut t223, t222)
	fe_mult(mut t223, t223, z) // 2^223 - 1

	mut x := Field{}
	fe_sqr(mut x, t223)
	for i := 1; i < 223; i++ {
		fe_sqr(mut x, x)
	}
	fe_mult(mut v, x, t222) // 2^446 - 2^222 - 1
}

// If u/v is square, fe_sqrtratio computes the square root r and returns (r, 1).
// If u/v is not a square, it returns (r, 0).
// In both cases, r is set to u * (u*v)^((p-3)/4) (mod p).
@[direct_array_access; inline]
fn fe_sqrtratio(mut r Field, u Field, v Field) (Field, int) {
	mut uv := Field{}
	fe_mult(mut uv, u, v)
	fe_power446(mut uv, uv)
	fe_mult(mut r, u, uv)

	// Check if v * r^2 == u
	mut ck := Field{}
	fe_sqr(mut ck, r)
	fe_mult(mut ck, v, ck)

	is_square := fe_cmp(ck, u)

	return r, is_square
}

// fe_abs return absolute value of u, ie, |u| (mod p)
@[direct_array_access; inline]
fn fe_abs(mut z Field, u Field) {
	mut x := Field{}
	fe_negate(mut x, u)
	fe_cselect(mut z, x, u, u.is_negative())
}

@[direct_array_access; inline]
fn (v Field) is_negative() int {
	mut x := Field{}
	fe_clone(mut x, v)
	fe_reduce(mut x)
	return int(x.el[0] & 1)
}

// Helpers
//

// mask_64bits returns u64(max_u64) if cond is 1, and 0 otherwise.
@[inline]
fn mask_64bits(cond int) u64 {
	return u64(0) - u64(cond)
}

// shift_right_by56 returns a >> 56. a is assumed to be below 128 bits.
@[inline]
fn shift_right_by56(mut a unsigned.Uint128) u64 {
	return (a.hi << 8) | (a.lo >> 56)
}

// add_128 adds a + b
@[inline]
fn add_128(a unsigned.Uint128, b unsigned.Uint128) unsigned.Uint128 {
	return a.add(b)
}

// lsh_128 does a << 1
@[inline]
fn lsh_128(a unsigned.Uint128) unsigned.Uint128 {
	return unsigned.uint128_new(a.lo << 1, (a.hi << 1) | (a.lo >> 63))
}

// lsh_256 does a << 2
@[inline]
fn lsh_256(a unsigned.Uint128) unsigned.Uint128 {
	return unsigned.uint128_new(a.lo << 2, (a.hi << 2) | (a.lo >> 62))
}

// mult_64 creates Uint128 from two's 64-bit product of a*b
@[inline]
fn mult_64(a u64, b u64) unsigned.Uint128 {
	hi, lo := bits.mul_64(a, b)
	return unsigned.uint128_new(lo, hi)
}

// mult_56 returns (lo, hi) where lo + hi * 2^56 = a * b
@[inline]
fn mult_56(a u64, b u32) (u64, u64) {
	hh, ll := bits.mul_64(a, u64(b))
	lo := ll & fe_masklow_56bits
	hi := (hh << 8) | (ll >> fe_limb_size)
	return lo, hi
}

// sub_128 subtracts b from a. Callers only use it when a >= b.
@[inline]
fn sub_128(a unsigned.Uint128, b unsigned.Uint128) unsigned.Uint128 {
	lo, borrow := bits.sub_64(a.lo, b.lo, 0)
	hi, _ := bits.sub_64(a.hi, b.hi, borrow)
	return unsigned.uint128_new(lo, hi)
}

// mul_4limb_schoolbook performs 4x4 limb schoolbook multiplication into a 7-element Uint128 array.
@[direct_array_access; inline]
fn mul_4limb_schoolbook(mut out [7]unsigned.Uint128, x0 u64, x1 u64, x2 u64, x3 u64, y0 u64, y1 u64, y2 u64, y3 u64) {
	// This routine accepts mut out [7]unsigned.Uint128, but it accumulates (add_128)
	// into out[i + j] without zeroing out first.
	// If out contains uninitialized memory or previous stack junk,
	// the products will be corrupted. so we initialize out to zero
	clear_uint128x7(mut out)
	mut x := [x0, x1, x2, x3]!
	mut y := [y0, y1, y2, y3]!
	for i := 0; i < 4; i++ {
		for j := 0; j < 4; j++ {
			out[i + j] = add_128(out[i + j], mult_64(x[i], y[j]))
		}
	}
	clear_u64x4(mut x)
	clear_u64x4(mut y)
}

// reduce_8limb_product reduces 8 128-bit accumulators down to an 8-limb 56-bit field element.
//
// Sequentially extracts full 128-bit carries (`(hi << 8) | (lo >> 56)`) to ensure zero
// upper-bit truncation before applying final Solinas reduction.
@[direct_array_access; inline]
fn reduce_8limb_product(mut z Field, mut t0 unsigned.Uint128, mut t1 unsigned.Uint128, mut t2 unsigned.Uint128, mut t3 unsigned.Uint128, mut t4 unsigned.Uint128, mut t5 unsigned.Uint128, mut t6 unsigned.Uint128, mut t7 unsigned.Uint128) {
	mut res := Field{}
	mut c := u64(0)

	// Step-by-step carry extraction across 128-bit limb accumulators
	t0 = t0.add(unsigned.uint128_new(c, 0))
	res.el[0] = t0.lo & fe_masklow_56bits
	c = (t0.hi << 8) | (t0.lo >> 56)

	t1 = t1.add(unsigned.uint128_new(c, 0))
	res.el[1] = t1.lo & fe_masklow_56bits
	c = (t1.hi << 8) | (t1.lo >> 56)

	t2 = t2.add(unsigned.uint128_new(c, 0))
	res.el[2] = t2.lo & fe_masklow_56bits
	c = (t2.hi << 8) | (t2.lo >> 56)

	t3 = t3.add(unsigned.uint128_new(c, 0))
	res.el[3] = t3.lo & fe_masklow_56bits
	c = (t3.hi << 8) | (t3.lo >> 56)

	t4 = t4.add(unsigned.uint128_new(c, 0))
	res.el[4] = t4.lo & fe_masklow_56bits
	c = (t4.hi << 8) | (t4.lo >> 56)

	t5 = t5.add(unsigned.uint128_new(c, 0))
	res.el[5] = t5.lo & fe_masklow_56bits
	c = (t5.hi << 8) | (t5.lo >> 56)

	t6 = t6.add(unsigned.uint128_new(c, 0))
	res.el[6] = t6.lo & fe_masklow_56bits
	c = (t6.hi << 8) | (t6.lo >> 56)

	t7 = t7.add(unsigned.uint128_new(c, 0))
	res.el[7] = t7.lo & fe_masklow_56bits
	c = (t7.hi << 8) | (t7.lo >> 56)

	// Reduce top carry using Solinas identity 2^448 = 2^224 + 1
	res.el[0] += c
	res.el[4] += c

	fe_carry_propagates(mut res)
	fe_clone(mut z, res)
}

@[direct_array_access; inline]
fn clear_u64x4(mut values [4]u64) {
	for i := 0; i < 4; i++ {
		values[i] = 0
	}
}

// clear_uint128x7 zeroes out a 7-element array of Uint128 values.
@[direct_array_access; inline]
fn clear_uint128x7(mut values [7]unsigned.Uint128) {
	zero := unsigned.uint128_new(0, 0)
	for i := 0; i < 7; i++ {
		values[i] = zero
	}
}

@[direct_array_access; inline]
fn clear_uint128x15(mut values [15]unsigned.Uint128) {
	zero := unsigned.uint128_new(0, 0)
	for i := 0; i < 15; i++ {
		values[i] = zero
	}
}
