// Copyright © 2026 blackshirt.
// Use of this source code is governed by an MIT license
// that can be found in the LICENSE file.
//
// This file provides a type-safe, higher-level key API on top of the raw
// `x448(scalar []u8, point []u8) ![]u8` function.
//
// RATIONALE
// ---------
// The free `x448()` function takes two `[]u8` arguments of identical shape:
// a secret scalar and a peer's public point. Nothing in the type system
// stops a caller from accidentally swapping them at a call site, e.g.:
//
//     shared := x448(their_public_key, my_private_key)! // compiles, wrong
//
// This silently produces a meaningless "shared secret" with no error and
// no crash -- exactly the kind of bug that survives code review and unit
// tests that only exercise the "happy path" with correctly-ordered args.
//
// `PrivateKey` and `PublicKey` are distinct nominal types wrapping the same
// 56-byte payload. The compiler now rejects a swapped call at compile time,
// since `PrivateKey.shared_secret(peer PublicKey)` only accepts a
// `PublicKey` in the peer position.
//
// The free `x448()` function and `validate_point()` remain available
// unchanged for callers who need raw byte-slice access (e.g. wire-protocol
// code that decodes key material into `[]u8` buffers directly, such as a
// TLS key_share extension parser).
module curve448

import crypto.rand

// PrivateKey represents an X448 secret scalar (56 bytes / 448 bits).
//
// The stored bytes are the *unclamped* input scalar as supplied by the
// caller (or generated by `generate_private_key`); clamping per RFC 7748
// (clearing the two low bits of the first byte and setting the high bit of
// the last byte) is applied internally by `x448()` on every use, matching
// the behavior of the free function.
//
// The struct is marked `@[noinit]` to prevent zero-initialized default construction.
@[noinit]
pub struct PrivateKey {
mut:
	// bytes holds the 56-byte unclamped raw scalar.
	bytes [56]u8
}

// PublicKey represents an X448 public point's u-coordinate (56 bytes / 448 bits).
//
// The stored bytes represent the little-endian u-coordinate of the public point.
// The struct is marked `@[noinit]` to prevent zero-initialized default construction.
@[noinit]
pub struct PublicKey {
mut:
	// bytes holds the 56-byte little-endian u-coordinate.
	bytes [56]u8
}

// new_private_key wraps a 56-byte secret scalar into a `PrivateKey`.
//
// Parameters:
//   b - Byte slice of length 56 containing the raw unclamped scalar.
//
// Errors:
//   - Returns an error if `b.len != 56`.
//
// Note: This performs no validation beyond length checks: any 56-byte value is a
// structurally valid X448 scalar input (clamping is applied at use time inside `x448()`).
@[direct_array_access]
pub fn new_private_key(b []u8) !PrivateKey {
	if b.len != scalar_size {
		return error('new_private_key: expected ${scalar_size} bytes, got ${b.len}')
	}
	mut pk := PrivateKey{}
	for i in 0 .. scalar_size {
		pk.bytes[i] = b[i]
	}
	return pk
}

// new_public_key wraps a 56-byte peer point into a `PublicKey`.
//
// Parameters:
//   b - Byte slice of length 56 containing the public point u-coordinate.
//
// Errors:
//   - Returns an error if `b.len != 56`.
//
// Note: Non-canonical or low-order points are accepted here (per RFC 7748, `x448()` reduces
// non-canonical points mod p automatically). Call `pub_key.validate()` explicitly if strict RFC 7748
// point validation is required before use.
@[direct_array_access]
pub fn new_public_key(b []u8) !PublicKey {
	if b.len != scalar_size {
		return error('new_public_key: expected ${scalar_size} bytes, got ${b.len}')
	}
	mut pub_key := PublicKey{}
	for i in 0 .. scalar_size {
		pub_key.bytes[i] = b[i]
	}
	return pub_key
}

// generate_private_key creates a new `PrivateKey` populated with 56 bytes from a CSPRNG.
//
// Returns:
//   A new `PrivateKey` populated with random scalar bytes.
//
// The returned scalar is unclamped raw random bytes; clamping happens at
// use time inside `x448()`, consistent with every other entry point here.
pub fn generate_private_key() !PrivateKey {
	raw := rand.bytes(scalar_size)!
	return new_private_key(raw)
}

// bytes returns a copy of the private key's raw scalar bytes.
//
// Returns:
//   A fresh 56-byte slice copy of the private scalar.
//
// Security note: The returned slice is a fresh heap allocation; the caller is responsible for
// zeroing it (e.g. via `secure_zero_buf`) once no longer needed, as ordinary GC does not zero memory.
pub fn (p PrivateKey) bytes() []u8 {
	return p.bytes[..].clone()
}

// bytes returns a copy of the public key's raw u-coordinate bytes.
//
// Returns:
//   A fresh 56-byte slice copy of the public key point.
pub fn (p PublicKey) bytes() []u8 {
	return p.bytes[..].clone()
}

// zero wipes this private key's scalar bytes in place using volatile memory writes.
//
// Call this once the key is no longer needed. After calling `zero()`, the
// key must not be used again (its backing bytes become all-zero).
pub fn (mut p PrivateKey) zero() {
	// NOTE: `p.bytes[..]` followed by `secure_zero_buf` would copy the
	// fixed array into a fresh dynamic-array header rather than aliasing
	// it, silently wiping a throwaway copy while leaving `p.bytes` intact.
	// Wipe the backing memory directly instead, matching the
	// `crypto_wipe_8xu64` pattern used for `Field` elsewhere.
	secure_zero_ptr(voidptr(&p.bytes[0]), scalar_size)
}

// validate checks that this public key encodes a canonical, non-low-order
// X448 point, per RFC 7748 strict validation rules. See `validate_point`
// for details on what is rejected.
pub fn (p PublicKey) validate() ! {
	validate_point(p.bytes[..])!
}

// public_key derives the `PublicKey` corresponding to this `PrivateKey`,
// i.e. the result of scalar-multiplying the standard Curve448 base point (u = 5).
//
// Returns:
//   Derived `PublicKey` containing the 56-byte u-coordinate point.
pub fn (priv PrivateKey) public_key() !PublicKey {
	out := x448(priv.bytes[..], base_point)!
	return new_public_key(out)
}

// shared_secret computes the X448 Diffie-Hellman shared secret between
// this private key and a peer's public key.
//
// Parameters:
//   peer - The peer's `PublicKey`.
//
// Returns:
//   56-byte slice containing the computed ECDH shared secret.
//
// Errors:
//   - Returns an error if scalar multiplication yields a low-order point (all-zero output).
//
// This is the recommended entry point for ECDH: unlike the free `x448()`
// function, the two arguments have distinct types, so a call site that
// accidentally swaps the private and public key arguments fails to
// compile instead of silently producing a bogus shared secret.
pub fn (priv PrivateKey) shared_secret(peer PublicKey) ![]u8 {
	return x448(priv.bytes[..], peer.bytes[..])
}
