// Copyright © 2026 blackshirt.
// Use of this source code is governed by an MIT license
// that can be found in the LICENSE file.
//
// This file provides a type-safe, higher-level key API on top of the raw
// `x448(scalar []u8, point []u8) ![]u8` function.
//
// RATIONALE
// ---------
// The free `x448()` function takes two `[]u8` arguments of identical shape:
// a secret scalar and a peer's public point. Nothing in the type system
// stops a caller from accidentally swapping them at a call site, e.g.:
//
//     shared := x448(their_public_key, my_private_key)! // compiles, wrong
//
// This silently produces a meaningless "shared secret" with no error and
// no crash -- exactly the kind of bug that survives code review and unit
// tests that only exercise the "happy path" with correctly-ordered args.
//
// `PrivateKey` and `PublicKey` are distinct nominal types wrapping the same
// 56-byte payload. The compiler now rejects a swapped call at compile time,
// since `PrivateKey.shared_secret(peer PublicKey)` only accepts a
// `PublicKey` in the peer position.
//
// The free `x448()` function and `validate_point()` remain available
// unchanged for callers who need raw byte-slice access (e.g. wire-protocol
// code that decodes key material into `[]u8` buffers directly, such as a
// TLS key_share extension parser).
module curve448

import crypto.rand

// PrivateKey represents an X448 secret scalar (56 bytes / 448 bits).
//
// The stored bytes are the *unclamped* input scalar as supplied by the
// caller (or generated by `generate_private_key`); clamping per RFC 7748
// (clearing the two low bits of the first byte and setting the high bit of
// the last byte) is applied internally by `x448()` on every use, matching
// the behavior of the free function.
@[noinit]
pub struct PrivateKey {
mut:
	bytes [56]u8
}

// PublicKey represents an X448 public point's u-coordinate (56 bytes).
@[noinit]
pub struct PublicKey {
mut:
	bytes [56]u8
}

// new_private_key wraps a 56-byte secret scalar into a `PrivateKey`.
//
// This performs no validation beyond length: any 56-byte value is a
// structurally valid X448 scalar input (clamping is applied at use time).
@[direct_array_access]
pub fn new_private_key(b []u8) !PrivateKey {
	if b.len != scalar_size {
		return error('new_private_key: expected ${scalar_size} bytes, got ${b.len}')
	}
	mut pk := PrivateKey{}
	for i in 0 .. scalar_size {
		pk.bytes[i] = b[i]
	}
	return pk
}

// new_public_key wraps a 56-byte peer point into a `PublicKey`.
//
// This performs no validation: non-canonical or low-order points are
// accepted here (per RFC 7748, `x448()` reduces non-canonical points mod p
// automatically). Call `.validate()` explicitly if strict RFC 7748 point
// validation is required before use.
@[direct_array_access]
pub fn new_public_key(b []u8) !PublicKey {
	if b.len != scalar_size {
		return error('new_public_key: expected ${scalar_size} bytes, got ${b.len}')
	}
	mut pub_key := PublicKey{}
	for i in 0 .. scalar_size {
		pub_key.bytes[i] = b[i]
	}
	return pub_key
}

// generate_private_key creates a new `PrivateKey` from a CSPRNG.
//
// The returned scalar is unclamped raw random bytes; clamping happens at
// use time inside `x448()`, consistent with every other entry point here.
pub fn generate_private_key() !PrivateKey {
	raw := rand.bytes(scalar_size)!
	return new_private_key(raw)
}

// bytes returns a copy of the private key's raw scalar bytes.
//
// The returned slice is a fresh copy; the caller is responsible for
// wiping it (e.g. via the module's `secure_zero_buf`-style handling) once
// it is no longer needed, since ordinary V garbage collection does not
// zero freed memory.
pub fn (p PrivateKey) bytes() []u8 {
	return p.bytes[..].clone()
}

// bytes returns a copy of the public key's raw point bytes.
pub fn (p PublicKey) bytes() []u8 {
	return p.bytes[..].clone()
}

// zero wipes this private key's scalar bytes in place.
//
// Call this once the key is no longer needed. After calling `zero`, the
// key must not be used again (its bytes become all-zero, which decodes to
// a valid-looking but cryptographically meaningless scalar).
pub fn (mut p PrivateKey) zero() {
	// NOTE: `p.bytes[..]` followed by `secure_zero_buf` would copy the
	// fixed array into a fresh dynamic-array header rather than aliasing
	// it, silently wiping a throwaway copy while leaving `p.bytes` intact.
	// Wipe the backing memory directly instead, matching the
	// `crypto_wipe_8xu64` pattern used for `Field` elsewhere.
	secure_zero_ptr(voidptr(&p.bytes[0]), scalar_size)
}

// validate checks that this public key encodes a canonical, non-low-order
// X448 point, per RFC 7748 strict validation rules. See `validate_point`
// for details on what is rejected.
pub fn (p PublicKey) validate() ! {
	validate_point(p.bytes[..])!
}

// public_key derives the public key corresponding to this private key,
// i.e. the result of scalar-multiplying the standard base point (u = 5).
pub fn (priv PrivateKey) public_key() !PublicKey {
	out := x448(priv.bytes[..], base_point)!
	return new_public_key(out)
}

// shared_secret computes the X448 Diffie-Hellman shared secret between
// this private key and a peer's public key.
//
// This is the recommended entry point for ECDH: unlike the free `x448()`
// function, the two arguments have distinct types, so a call site that
// accidentally swaps the private and public key arguments fails to
// compile instead of silently producing a bogus shared secret.
//
// Returns an error if the resulting point is a low-order point (see
// `x448()` for details).
pub fn (priv PrivateKey) shared_secret(peer PublicKey) ![]u8 {
	return x448(priv.bytes[..], peer.bytes[..])
}
